# Basic
title: yuxiang
subtitle: Just do IT later.
welcome_message: 欢迎来到我的魔法世界! 
description: 嗨，我是 yuxiang，ios Dev，非著名程序员。
creator: <a href="http://www.yu09.i">yuxiang</a>

url: "http://www.yu09.in"

permalink: /:categories/:title

# Format
highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: GitHub,     in_site: false,  description: yuxiang's GitHub,    url: 'https://github.com/yu8200'}
    - {title: 目录,        in_site: true,  description: 博客目录,               url: '/timeline'}
    - {title: 关于,        in_site: true,  description: 关于作者 yuxiang,       url: '/info/about'}
    


gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-redirect-from

# Pagination
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: yuxiang
    # duoshuo:
# Social
social:
    weibo: yuxiang
    github: yuxiang
    twitter: yuxiang
    rss: /feed.xml
    mail: yuxiang@gmail.com
    copyright: http://choosealicense.online

# Google Analytics
future: true
ga:
    id: UA-8233223-3
    host: www.ty09.in
